-- AlterTable
ALTER TABLE "visits" ALTER COLUMN "weather_clear_h" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "weather_cloudy_h" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "weather_drizzle_h" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "weather_rain_h" SET DATA TYPE DOUBLE PRECISION;
